---

collections:
  - name: community.windows
    version: 2.3.0
  - name: ansible.windows
    version: 2.5.0
  - name: community.docker
    version: 4.0.1
  - name: chocolatey.chocolatey
    version: 1.5.3

