name: Build and publish production container
run-name: Release
on: 
  pull_request:
    types: 
     - closed
    branches:
      - 'main'
    tags: 
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  Release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    outputs:
      test_tag: ${{ steps.gen_version.outputs.TEST_TAG }}

    steps:

      - name: set values
        id: gen_version
        run: |
          echo "TEST_TAG=${{ github.head_ref }}" | tr / - >> $GITHUB_OUTPUT
      - name: Use the value
        # this sets environment variables for this step
        env:
          TEST_TAG: ${{ steps.gen_version.outputs.TEST_TAG }}
        run: |
          echo "${TEST_TAG}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        id: push
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Remove all older containers
        uses: actions/delete-package-versions@v5
        with: 
          package-name: 'container-devops'
          package-type: 'container'
          delete-only-untagged-versions: 'true'
          min-versions-to-keep: 2

      - name: Delete image
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          # NOTE: at now only orgs is supported
          name: container-devops
          owner: Patrick8079
          # NOTE: using Personal Access Token
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.gen_version.outputs.TEST_TAG }}